source 'https://rubygems.org'

ruby '~> 2.7.5'
gem 'active_model_serializers'
gem 'activerecord-import' # allows `Model.import`
gem 'activerecord-mysql-reconnect'
gem 'active_record_union' # allows `[query].union([query])`
gem 'amazing_print'
gem 'annotate'
gem 'arabic-letter-connector'
gem 'ar-find-in-batches-with-order'
gem 'asset_sync' # mirrors assets in S3 (contrary to docs, do not put this in group :assets)
gem 'attr_encrypted'
gem 'attr_json'
gem 'authtrail'
gem 'aws-sdk-cloudwatch'
gem 'aws-sdk-core'
gem 'aws-sdk-ec2'
gem 'aws-sdk-elasticloadbalancingv2'
gem 'aws-sdk-lambda'
gem 'aws-sdk-opsworks'
gem 'aws-sdk-rds'
gem 'aws-sdk-s3'
gem 'aws-sdk-secretsmanager'
gem 'aws-sdk-ses'
gem 'aws-ses'
gem 'bcrypt'
gem 'better_errors' # Error reporting gems
gem 'binding_of_caller'
gem 'blazer'
gem 'bootsnap'
gem 'bootstrap-email', '~> 0.3.2'
gem 'boxr'
gem 'brakeman'
gem 'browser' # User Agent (UA) / Browser detection
gem 'bump'
gem 'bundler-audit'
gem 'cancancan'
gem 'chroma'
gem 'clamd'
gem 'cloudflare-rails'
gem 'colorize'
gem 'connection_pool'
gem 'countries'
gem 'database_cleaner'
gem 'ddtrace', require: 'ddtrace/auto_instrument'
gem 'debase'
gem 'devise'
gem 'devise_invitable'
gem 'devise-two-factor'
gem 'dogstatsd-ruby'
gem 'factory_bot_rails'
gem 'faker'
gem 'ffaker'
gem 'ffi' # C++ library interaction
gem 'figaro'
gem 'fog-aws'
gem 'foreman'
gem 'geo_coord'
gem 'git-revision'
gem 'google-api-client'
gem 'googleauth'
gem 'google-id-token'
gem 'google-protobuf', '~> 3.19'
gem 'groupdate'
gem 'guard', '>= 2.2.2', require: false
gem 'guard-minitest', require: false
gem 'guard-rspec', require: false
gem 'haikunator'
gem 'hash_dot'
gem 'hashids'
gem 'htmlcompressor' #removes whitespace from html responses
gem 'httparty'
gem 'jbuilder'
gem 'jsonapi-serializer'
gem 'jwt'
gem 'kaminari' # Active Record pagination (ex: [query].page(1).per(25))
gem 'kramdown'
gem 'kramdown-converter-pdf'
gem 'letter_avatar'
gem 'letter_opener'
gem 'letter_opener_web'
gem 'listen'
gem 'lograge'
gem 'logstash-event'
gem 'marcel', '~> 1.0.1'
gem 'meta_request'
gem 'meta-tags'
gem 'mini_magick'
gem 'mini_racer', '= 0.4'
gem 'minitest'
gem 'minitest-rails'
gem 'mjml-rails'
gem 'mysql2'
gem 'mysql-binuuid-rails'
gem 'nokogiri'
gem 'numbers_and_words'
gem 'obscenity'
gem 'oga'
gem 'omniauth'
gem 'omniauth-box-oauth2'
gem 'omniauth-dropbox-oauth2', git: 'https://github.com/vzctl/omniauth-dropbox-oauth2.git', branch: 'api2_support'
gem 'omniauth-google-oauth2', '~> 0.8.0'
gem 'omniauth-multi-provider'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-saml'
gem 'paperclip'
gem 'phaxio', '~> 2.0.0'
gem 'phonelib'
gem 'phony' # Useful for formatting phone numbers
gem 'posix-spawn', '~> 0.3.15'
gem 'premailer-rails' # cleans up email view code
gem 'prerender_rails'
gem 'prettier'
gem 'pry'
gem 'pry-remote'
gem 'public_suffix'
gem 'puma'
gem 'rack-attack'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 6.1.4'
gem 'rails-controller-testing'
gem 'rails-i18n'
gem 'rails_real_favicon'
gem 'rainbow'
gem 'rake'
gem 'ransack'
gem 'ratelimit'
gem 'rb-fsevent', require: false
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redis'
gem 'redis-objects'
gem 'redlock'
gem 'require_reloader'
gem 'responders'
gem 'retries'
gem 'rmagick'
gem 'rspec-rails'
gem 'rspec-sidekiq'
gem 'rubocop', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-rspec', require: false
gem 'ruby-debug-ide'
gem 'ruby-saml'
gem 'rubyzip'
gem 'sanitize'
gem 'sassc'
gem 'sassc-rails'
gem 'sdoc', require: false
gem 'secure_headers'
gem 'shoulda-matchers', '~> 3.1'
gem 'sidekiq-cron'
gem 'sidekiq-limit_fetch',
    git: 'https://github.com/optimumenergyco/sidekiq-limit_fetch.git',
    ref: '67e1810696845ae8bcd64b10e98d1fa140978e54'
gem 'sidekiq-logstash'
gem 'sidekiq-pro', source: 'https://f216a7b6:a43ab77a@gems.contribsys.com/'
gem 'sidekiq-status'
gem 'sidekiq-unique-jobs'
gem 'simple_token_authentication'
gem 'sinatra', require: false
gem 'sitemap_generator'
gem 'solargraph' # use with Atom package: ruby-solargraph
gem 'sprockets', '~> 3'
gem 'sqreen'
gem 'stripe'
gem 'sys-filesystem' #Used by /health-check for system info:  https://github.com/djberg96/sys-filesystem
gem 'terminal-notifier-guard', require: false
gem 'trend'
gem 'ttfunk'
gem 'turnout' # Allows us to toggle maintence mode https://github.com/biola/turnout
gem 'twilio-ruby' # Text message service
gem 'twitter' # used for release notes
gem 'uglifier'
gem 'unicode-blocks'
gem 'unicode-emoji'
gem 'utf8-cleaner'
gem 'vcr'
gem 'web-console'
gem 'webmock'
gem 'xml-simple' #Used in Compiler.rb
gem 'zaru'
gem 'zendesk_api'
